#!/bin/sh

RABBITMQ_HOST=${RABBITMQ_HOST:=rabbitmq}
RABBITMQ_PORT=${RABBITMQ_PORT:=3000}

# run dbus-daemon
mkdir -p /var/run/dbus/
dbus-daemon --system

# run knotd and inetbrd
inetbrd -n &
LD_LIBRARY_PATH=/usr/lib64 knotd -nr -R amqp://$RABBITMQ_HOST:$RABBITMQ_PORT
